src/objects/Three_Pointer__c.object
<CustomObject>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>MADE</fullName>
                </value>
                <value>
                    <fullName>MISSED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Three Pointer</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Three Pointer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Three Pointers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ThreePointerListControllerExt.cls
public with sharing class ThreePointerListControllerExt {

  private ApexPages.StandardSetController standardSetController;

  public ThreePointerListControllerExt(ApexPages.StandardSetController stdSetController) {
    this.standardSetController = stdSetController;
  }

  public PageReference madeAll() {
    List<Three_Pointer__c> selectedListViewRecords = (List<Three_Pointer__c>)standardSetController.getSelected();
    for(Three_Pointer__c record : selectedListViewRecords) {
      record.Result__c = 'MADE';
    }
    update selectedListViewRecords;
    return new PageReference('/'+ApexPages.currentPage().getParameters().get('retURL'));
  }

  public PageReference missedAll() {
    List<Three_Pointer__c> selectedListViewRecords = (List<Three_Pointer__c>)standardSetController.getSelected();
    for(Three_Pointer__c record : selectedListViewRecords) {
      record.Result__c = 'MISSED';
    }
    update selectedListViewRecords;
    return new PageReference('/'+ApexPages.currentPage().getParameters().get('retURL'));
  }
}