src/objects/Three_Pointer__c.object
<CustomObject>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>MADE</fullName>
                </value>
                <value>
                    <fullName>MISSED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Three Pointer</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Three Pointer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Three Pointers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ThreePointerControllerExt.cls
public with sharing class ThreePointerControllerExt {

  private final Three_Pointer__c mysObject;

  public ThreePointerControllerExt(ApexPages.StandardController stdController) {
    this.mysObject = (Three_Pointer__c)stdController.getRecord();
  }

  public PageReference made() {
    mysObject.Result__c = 'MADE';
    update mysObject;
    return new PageReference('/'+mysObject.get('id'));
  }

  public PageReference missed() {
    mysObject.Result__c = 'MISSED';
    update mysObject;
    return new PageReference('/'+mysObject.get('id'));
  }
}